spring:
  application:
    name: tbankApp
  datasource:
    url: jdbc:postgresql://localhost:5432/tbank_db
    username: postgres
    password: postgres
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
server:
  port: 8080