server:
  error:
    include-message: always
  port: 8081
  servlet:
    context-path: /bank-api
spring:
  application:
    name: bankApp
  datasource:
    url: jdbc:postgresql://localhost:5432/tbank_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
springdoc:
  swagger-ui:
    path: /swagger-ui.html
jwt:
  secret: 3f4b2a7e8f1c3d2a0b5e6c8f2087a4d9c6e5f0bcb16a14f22986f4084e6c6a2d
  lifetime: 30d
flyway:
  locations: classpath:db/migration