server:
  error:
    include-message: always
  servlet:
    context-path: /bank-api
  port: 8081
spring:
  application:
    name: bankApp
  datasource:
    # ДЛЯ ЛОКАЛЬНЫХ ТЕСТОВ
#    url: jdbc:postgresql://localhost:6543/bank_db
    url: jdbc:postgresql://bankDB/bank_db
    username: postgres
    password: secret
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    locations: classpath:db/migration
springdoc:
  swagger-ui:
    path: /swagger-ui.html
jwt:
  secret: 3f4b2a7e8f1c3d2a0b5e6c8f2087a4d9c6e5f0bcb16a14f22986f4084e6c6a2d
  lifetime: 30d